### ISSUE TITLE
Processor interface missing fields

### ISSUE THREAD

**Issue by AdamHerrmann** [angular/dgeni#165]
The definition for [`Processor`](https://github.com/angular/dgeni/blob/master/src/Processor.ts#L5_L10), seems to be missing several of the fields described in the documentation for [Package#processor](https://github.com/angular/dgeni/blob/master/src/Package.ts#L38_L46).  Also, I think the `$process` method should be listed as optional.

```typescript
import {Package} from 'dgeni';

export default new Package('example')
  .processor({name: 'works', $process() {}})

  .processor({name: 'does-not-work'})

  .processor({name: 'also-does-not-work', $process() {}, $runBefore: ['works']})

  .processor({name: 'still-does-not-work', $process() {}, $runAfter: ['works']})
;
```

I would be happy to submit a PR for this issue if that would be helpful.

**Comment by petebacondarwin** [comment]
That would be great thanks @AdamHerrmann !

**Comment by dherges** [comment]
Is it possible to publish a version for it?

[`0.4.7` is behind this great change](https://github.com/angular/dgeni/commits/master)...

**Comment by petebacondarwin** [comment]
Done :-)

**Comment by dherges** [comment]
Thank you so much!

Cheers w/ 🍻 ! :-)

**Comment by dherges** [comment]
Ah, something went missing. In `src/Processor.ts` It's included. In `lib/Processor.d.ts` is still missing the fields.

```
export interface Processor {
    $process(docs: DocCollection): DocCollection | void;
    name?: string;
    description?: string;
    $package?: string;
}
```

https://registry.yarnpkg.com/dgeni/-/dgeni-0.4.8.tgz#89670b580e99627aa40459574bb44db8db15f8e3

**Comment by petebacondarwin** [comment]
Darn it!
0.4.9 seems fixed: https://unpkg.com/dgeni@0.4.9/lib/Processor.d.ts

**Comment by dherges** [comment]
Yes!

Have a good night!
